#!/bin/bash
description="$(gettext -s "\e[1mQuesto script rimuove i metadati cattivi dai files\e[0m, anche conosciuti come\n\"Copyright\" (obbligo al non-uso/non-divulgazione).\nSebbene il riconoscimento delle fonti è un atto più che doveroso e legittimo,\nil Copyright e il \"diritto d'autore\" sono un'invenzione diabolica dell'Impero\ndi Alpha Draconis per impedire la divulgazione della conoscenza tra le persone e\nobbligarle a sottostare alle sue leggi draconiane e al terribile sistema di\ndominio attraverso la finanza a debito.\n\nCrediamo fermamente alla libera conoscenza e siamo contrari ad ogni sua forma di\nimpedimento.\nSe hai un file - qualunque esso sia - è una pura forma di conoscenza e non devi\nsentirti obbligato/a ad alcunché.")"
missing_operator="$(gettext -s "Manca l'operatore principale.")"
missing_file_or_directory="$(gettext -s "Manca un file o una directory da esaminare.")"
syntax="$(gettext -s "Sintassi:")"
istructions="$(gettext -s "non sembra essere installato, procedere con l'installazione? [y|n]")"
correctly_installed="$(gettext -s "installato correttamente")"
please_reply="$(gettext -s "Per cortesia rispondi: digita \"y\" per \"Sì\" o \"n\" per \"No\".")"
proceed_with_cleaning="$(gettext -s "Procedo con la pulizia...")"
is_a_dir__clean="$(gettext -s "è una \e[1mdirectory\e[0m. Pulizia ricorsiva...")"
is_a_file__clean="$(gettext -s "è un \e[1mfile\e[0m, lo pulisco...")"
is_not_a_valid_directory="$(gettext -s "non è un file o una directory valida")"
done="$(gettext -s "Fatto!")"
metadata_read="$(gettext -s "Lettura dei metadati:")"
