#!/bin/bash
LC_ALL="it_IT.UTF-8"
LANG="it_IT.UTF-8"
LANGUAGE="it_IT:en"

export LC_ALL LANG LANGUAGE LC_PAPER LESSCHARSET MM_CHARSET
export TEXTDOMAINDIR=./
export TEXTDOMAIN=lang_file.sh
. lang_file.sh

# Exiftool commands
# @see https://exiftool.org/TagNames.pdf
# ----------------------------------------------------------------------------

declare -A osInfo;
osInfo[/etc/redhat-release]="yum"
osInfo[/etc/arch-release]="pacman"
osInfo[/etc/gentoo-release]="emerge"
osInfo[/etc/SuSE-release]="zypp"
osInfo[/etc/debian_version]="apt-get"
osInfo[/etc/alpine-release]="apk"
for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        package_manager=${osInfo[$f]}
    fi
done

# Correct args if the filepath does not exists
if [ ! -f "$2" ] && [ ! -d "$2" ]; then
  for ARG in "$@"; do
    if [ "$ARG" != "$1" ]; then
      filepath+=$ARG
    fi
  done
else
  filepath=$2
fi

# ----------------------------------------------------------------------------

echo ""
echo -e "\e[36m================================================================================\e[0m"
echo -e "\e[1;33m
                                 ,    ,^.    .
                               ,'|  _ \ / _  |\`.
                              / /  \`.\| |/,'  \ \\
                             / :     \`. ,'     : \\
                            :  |      | |      |  :
                            |  :      ; :      ;  |
                            :   \`.__,'   \`.__,'   ;
                             \                   /
                              \                 /
                               \`.             ,'
                                 \`-._______,-'

                              JOIN THE RESISTANCE
\e[0m"
echo -e "\e[1;36m--------------------------------------------------------------------------------\e[0m"
echo -e "$description"
echo -e "\e[36m================================================================================\e[0m"
echo ""

if [ ! "$1" ] || [ ! "$2" ] ; then
  if [ "$1" != "read" ] && [ "$1" != "clean" ]; then
    echo -e "\e[31m\e[1m×\e[0m \e[31m$missing_operator\e[0m"
  fi
  if [ ! "$2" ] ; then
    echo -e "\e[31m\e[1m×\e[0m \e[31m$missing_file_or_directory\e[0m"
  fi

  echo ""
  echo "$syntax"
  echo -e "  \e[38;5;240m\$\e[0m ./strip_exif [\e[92mread\e[0m|\e[93mclean\e[0m] \e[96mfile\e[0m|\e[96mdirectory\e[0m"
  echo ""
  exit
fi

# Check if package is not installed
pkg="exiftool"
package_installed=$(dpkg-query -l | grep "$pkg" | wc -l)
if [ "$package_installed" -eq 0 ]; then
  while true; do
    # Ask if user wants to install it
    read -p "$pkg $istructions " yn
    case $yn in
      [Yy]* )
        sudo $package_manager install -y $pkg

        # Ok the package is installed
        if [ "$package_installed" -eq 1 ]; then
          echo ""
          echo "--------------------------------------------------------------------------------"
          echo "$pkg $correctly_installed."
          echo ""
        fi
        break;;
      [Nn]* )
        echo "Ok, ciao :)"
        exit;;
      * ) echo $please_reply;;
    esac
  done
fi

# ----------------------------------------------------------------------------

if [ "$1" == "clean" ]; then
  read -r -d '' strip_data << EOF
-AOCopyrightNotice=
-AOCurrentCopyrightOwnerId=
-AOCurrentCopyrightOwnerName=
-AOCurrentCopyrightOwnerName=
-AOCurrentLicensorId=
-AOCurrentLicensorName=
-ArtworkCopyrightNotice=
-ArtworkCopyrightOwnerID=
-copyright=
-Copyright=
-CopyrightFileName=
-CopyrightFlag=
-CopyrightLen=
-CopyrightLicenseCountryCode=
-CopyrightLicenseRegionCode=
-CopyrightLicenseRegionName=
-CopyrightNotice=
-CopyrightOwner=
-CopyrightOwnerID=
-CopyrightOwnerImageID=
-CopyrightOwnerName=
-CopyrightRegistrationNumber=
-CopyrightStatus=
-CopyrightStatus=
-CopyrightURL=
-CopyrightYear=
-CurrentIPTCDigest=
-HistoryAction=
-HistoryInstanceID=
-IPTCDigest=
-LegalCopyright=
-LegalCopyrights=
-LegalTrademark=
-LegalTrademarks=
-lookCopyright=
-LookCopyright=
-MDItemCopyright=
-ProfileCopyright=
-ProviderCopyright=
-RecordingCopyright=
-Trademark=
-Trademarks=

-comment=
-Comment=
-description=
-Description=
-keywords=
-notes=
-Notes=
-rights=
-Rights=
-Warning=

-Producer=

-ifd0:all=
-iptc:all=
-xmp:all=
--copyright
EOF
# -api "filter=s/[©®™]/ /g"

  echo ""
  echo $proceed_with_cleaning
  echo ""

  # Check if passed filepath is a file or a directory
  if [ -d "$filepath" ]; then
    echo -e "$filepath $is_a_dir__clean"
    echo ""
    # Run exiftool command
    exiftool -r -m -P -overwrite_original "$strip_data" "$filepath"
    # Read all metadata and output to file
    exiftool -r "$filepath" > "strip_exif_data.txt"
  elif [ -f "$filepath" ]; then
    echo -e "$filepath è$is_a_file__clean"
    echo ""
    exiftool -m -P -overwrite_original "$strip_data" "$filepath"
    # Read all metadata and output to file
    exiftool "$filepath" > "strip_exif_data.txt"
  else
    echo "$filepath $is_not_a_valid_directory"
    echo "";
  fi

  echo ""
  echo -e "\e[32m$done\e[0m"
  echo ""
fi

if [ "$1" == "read" ] || [ "$1" == "clean" ]; then
  echo -e "\e[34m$metadata_read\e[0m"

  exiftool "$filepath"
fi
